/* tslint:disable */
/* eslint-disable */
/**
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)?
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import globalAxios, {
  AxiosPromise,
  AxiosInstance,
  AxiosRequestConfig,
} from "axios";
import { Configuration } from "../configuration";
import FormData = require("form-data");
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
  valueToString,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
} from "../base";
// @ts-ignore
import { IntlVerification } from "../models";
// @ts-ignore
import { IntlVerificationWritable } from "../models";
// @ts-ignore
import { IntlVerifications } from "../models";
// @ts-ignore
import { IntlVerificationsPayload } from "../models";
// @ts-ignore
import { LobError } from "../models";
/**
 * IntlVerificationsApi - axios parameter creator
 * @export
 */
export const IntlVerificationsApiAxiosParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     * Verify a list of international (except US or US territories) address with a live API key.
     * @summary verifyBulk
     * @param {IntlVerificationsPayload} intlVerificationsPayload
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    bulkIntlVerifications: async (
      intlVerificationsPayload: IntlVerificationsPayload,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'intlVerificationsPayload' is not null or undefined
      assertParamExists(
        "bulkIntlVerifications",
        "intlVerificationsPayload",
        intlVerificationsPayload
      );
      const localVarPath = `/bulk/intl_verifications`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        intlVerificationsPayload,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Verify an international (except US or US territories) address with a live API key.
     * @summary verifySingle
     * @param {IntlVerificationWritable} intlVerificationWritable
     * @param {'native' | 'match'} [xLangOutput] * &#x60;native&#x60; - Translate response to the native language of the country in the request * &#x60;match&#x60; - match the response to the language in the request  Default response is in English.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    intlVerification: async (
      intlVerificationWritable: IntlVerificationWritable,
      xLangOutput?: "native" | "match",
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'intlVerificationWritable' is not null or undefined
      assertParamExists(
        "intlVerification",
        "intlVerificationWritable",
        intlVerificationWritable
      );
      const localVarPath = `/intl_verifications`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication basicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      if (xLangOutput !== undefined && xLangOutput !== null) {
        localVarHeaderParameter["x-lang-output"] = String(xLangOutput);
      }

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        intlVerificationWritable,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * IntlVerificationsApi - functional programming interface
 * @export
 */
export const IntlVerificationsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator =
    IntlVerificationsApiAxiosParamCreator(configuration);
  return {
    /**
     * Verify a list of international (except US or US territories) address with a live API key.
     * @summary verifyBulk
     * @param {IntlVerificationsPayload} intlVerificationsPayload
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async bulkIntlVerifications(
      intlVerificationsPayload: IntlVerificationsPayload,
      options?: AxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<IntlVerifications>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.bulkIntlVerifications(
          intlVerificationsPayload,
          options
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
    /**
     * Verify an international (except US or US territories) address with a live API key.
     * @summary verifySingle
     * @param {IntlVerificationWritable} intlVerificationWritable
     * @param {'native' | 'match'} [xLangOutput] * &#x60;native&#x60; - Translate response to the native language of the country in the request * &#x60;match&#x60; - match the response to the language in the request  Default response is in English.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async intlVerification(
      intlVerificationWritable: IntlVerificationWritable,
      xLangOutput?: "native" | "match",
      options?: AxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<IntlVerification>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.intlVerification(
          intlVerificationWritable,
          xLangOutput,
          options
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
  };
};

/**
 * IntlVerificationsApi - object-oriented interface
 * @export
 * @class IntlVerificationsApi
 * @extends {BaseAPI}
 */
export class IntlVerificationsApi extends BaseAPI {
  /**
   * Verify a list of international (except US or US territories) address with a live API key.
   * @summary verifyBulk
   * @param {IntlVerificationsPayload} intlVerificationsPayload
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof IntlVerificationsApi
   */
  public verifyBulk(
    intlVerificationsPayload: IntlVerificationsPayload,
    options?: AxiosRequestConfig
  ) {
    return IntlVerificationsApiFp(this.configuration)
      .bulkIntlVerifications(intlVerificationsPayload, options)
      .then((request) => request(this.axios, this.basePath))
      .then(function (response) {
        return new IntlVerifications(response.data);
      })
      .catch((error) => {
        if (error.response?.data?.error?.message) {
          error.message = error.response.data.error.message;
        }
        throw error;
      });
  }

  /**
   * Verify an international (except US or US territories) address with a live API key.
   * @summary verifySingle
   * @param {IntlVerificationWritable} intlVerificationWritable
   * @param {'native' | 'match'} [xLangOutput] * &#x60;native&#x60; - Translate response to the native language of the country in the request * &#x60;match&#x60; - match the response to the language in the request  Default response is in English.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof IntlVerificationsApi
   */
  public verifySingle(
    intlVerificationWritable: IntlVerificationWritable,
    xLangOutput?: "native" | "match",
    options?: AxiosRequestConfig
  ) {
    return IntlVerificationsApiFp(this.configuration)
      .intlVerification(intlVerificationWritable, xLangOutput, options)
      .then((request) => request(this.axios, this.basePath))
      .then(function (response) {
        return new IntlVerification(response.data);
      })
      .catch((error) => {
        if (error.response?.data?.error?.message) {
          error.message = error.response.data.error.message;
        }
        throw error;
      });
  }
}

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
