/* tslint:disable */
/* eslint-disable */
/**
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AddressUsAllOf
 */
export class AddressUsAllOf {
    /**
     * Unique identifier prefixed with `adr_`.
     * @type {string}
     * @memberof AddressUsAllOf
     */
    private '_id': string;
    public get id() { return (this._id); }
    public set id(newValue: string) {
        if(newValue && !/^adr_[a-zA-Z0-9]+$/.test(newValue)) {
            throw new Error("Invalid id provided");
        }
        this._id = newValue;
    }
    /**
     * 
     * @type {string}
     * @memberof AddressUsAllOf
     */
    'object'?: string;
    /**
     * An internal description that identifies this resource. Must be no longer than 255 characters. 
     * @type {string}
     * @memberof AddressUsAllOf
     */
    'description'?: string | null;
    /**
     * Either `name` or `company` is required, you may also add both. Must be no longer than 40 characters. If both `name` and `company` are provided, they will be printed on two separate lines above the rest of the address. 
     * @type {string}
     * @memberof AddressUsAllOf
     */
    'name'?: string | null;
    /**
     * Either `name` or `company` is required, you may also add both. Must be no longer than 40 characters. If both `name` and `company` are provided, they will be printed on two separate lines above the rest of the address. This field can be used for any secondary recipient information which is not part of the actual mailing address (Company Name, Department, Attention Line, etc). 
     * @type {string}
     * @memberof AddressUsAllOf
     */
    'company'?: string | null;
    /**
     * Must be no longer than 40 characters.
     * @type {string}
     * @memberof AddressUsAllOf
     */
    'phone'?: string | null;
    /**
     * Must be no longer than 100 characters.
     * @type {string}
     * @memberof AddressUsAllOf
     */
    'email'?: string | null;
    /**
     * The primary number, street name, and directional information.
     * @type {string}
     * @memberof AddressUsAllOf
     */
    'address_line1': string;
    /**
     * An optional field containing any information which can\'t fit into line 1.
     * @type {string}
     * @memberof AddressUsAllOf
     */
    'address_line2'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressUsAllOf
     */
    'address_city': string;
    /**
     * 2 letter state short-name code
     * @type {string}
     * @memberof AddressUsAllOf
     */
    private '_address_state': string;
    public get address_state() { return (this._address_state); }
    public set address_state(newValue: string) {
        if(newValue && !/^[a-zA-Z]{2}$/.test(newValue)) {
            throw new Error("Invalid address_state provided");
        }
        this._address_state = newValue;
    }
    /**
     * Must follow the ZIP format of `12345` or ZIP+4 format of `12345-1234`. 
     * @type {string}
     * @memberof AddressUsAllOf
     */
    private '_address_zip': string;
    public get address_zip() { return (this._address_zip); }
    public set address_zip(newValue: string) {
        if(newValue && !/^\d{5}(-\d{4})?$/.test(newValue)) {
            throw new Error("Invalid address_zip provided");
        }
        this._address_zip = newValue;
    }
    /**
     * Full name of country
     * @type {string}
     * @memberof AddressUsAllOf
     */
    'address_country'?: AddressUsAllOfAddressCountryEnum;
    /**
     * Use metadata to store custom information for tagging and labeling back to your internal systems. Must be an object with up to 20 key-value pairs. Keys must be at most 40 characters and values must be at most 500 characters. Neither can contain the characters `\"` and `\\`. i.e. \'{\"customer_id\" : \"NEWYORK2015\"}\' Nested objects are not supported.  See [Metadata](#section/Metadata) for more information.
     * @type {{ [key: string]: string; }}
     * @memberof AddressUsAllOf
     */
    'metadata'?: { [key: string]: string; };
    /**
     * Only returned for accounts on certain <a href=\"https://dashboard.lob.com/#/settings/editions\">Print &amp; Mail Editions</a>. Value is `true` if the address was altered because the recipient filed for a <a href=\"#ncoa\">National Change of Address (NCOA)</a>, `false` if the NCOA check was run but no altered address was found, and `null` if the NCOA check was not run. The NCOA check does not happen for non-US addresses, for non-deliverable US addresses, or for addresses created before the NCOA feature was added to your account. 
     * @type {boolean}
     * @memberof AddressUsAllOf
     */
    'recipient_moved'?: boolean | null;
}

/**
    * @export
    * @enum {string}
    */
export enum AddressUsAllOfAddressCountryEnum {
    UnitedStates = 'UNITED STATES'
}



/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

