/* tslint:disable */
/* eslint-disable */
/**
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BillingGroup
 */
export interface BillingGroup {
    /**
     * Description of the billing group.
     * @type {string}
     * @memberof BillingGroup
     */
    'description'?: string;
    /**
     * Name of the billing group.
     * @type {string}
     * @memberof BillingGroup
     */
    'name'?: string;
    /**
     * Unique identifier prefixed with `bg_`.
     * @type {string}
     * @memberof BillingGroup
     */
    'id'?: string;
    /**
     * A timestamp in ISO 8601 format of the date the resource was created.
     * @type {string}
     * @memberof BillingGroup
     */
    'date_created'?: string;
    /**
     * A timestamp in ISO 8601 format of the date the resource was last modified.
     * @type {string}
     * @memberof BillingGroup
     */
    'date_modified'?: string;
    /**
     * Value is resource type.
     * @type {string}
     * @memberof BillingGroup
     */
    'object'?: BillingGroupObjectEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum BillingGroupObjectEnum {
    BillingGroup = 'billing_group'
}



/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

