/* tslint:disable */
/* eslint-disable */
/**
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)?
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as Models from "./index";

/**
 *
 * @export
 * @class BuckslipEditable
 */
export class BuckslipEditable {
  constructor(input?: any) {
    if (typeof input?.front !== "undefined") {
      this.front = input.front;
    }
    if (typeof input?.back !== "undefined") {
      this.back = input.back;
    }
    if (typeof input?.description !== "undefined") {
      this.description = input.description;
    }
    if (typeof input?.size !== "undefined") {
      this.size = input.size;
    }
  }

  /**
   * A PDF template for the front of the buckslip
   * @type {string}
   * @memberof BuckslipEditable
   */
  "front": string;

  /**
   * A PDF template for the back of the buckslip
   * @type {string}
   * @memberof BuckslipEditable
   */
  "back"?: string;

  /**
   * Description of the buckslip.
   * @type {string}
   * @memberof BuckslipEditable
   */
  "description"?: string | null;

  /**
   * The size of the buckslip
   * @type {string}
   * @memberof BuckslipEditable
   */
  "size"?: BuckslipEditableSizeEnum;

  public toJSON() {
    let out = {};
    for (const [key, value] of Object.entries(this)) {
      out = Object.assign({}, out, {
        [key[0] === "_" ? key.substr(1, key.length) : key]: value,
      });
    }
    return out;
  }
}

/**
 * @export
 * @enum {string}
 */
export enum BuckslipEditableSizeEnum {
  _875x375 = "8.75x3.75",
}

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
