/* tslint:disable */
/* eslint-disable */
/**
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CardOrder
 */
export interface CardOrder {
    /**
     * Unique identifier prefixed with `co_`.
     * @type {string}
     * @memberof CardOrder
     */
    'id'?: string;
    /**
     * Unique identifier prefixed with `card_`.
     * @type {string}
     * @memberof CardOrder
     */
    'card_id'?: string;
    /**
     * The status of the card order.
     * @type {string}
     * @memberof CardOrder
     */
    'status'?: CardOrderStatusEnum;
    /**
     * The inventory of the card order.
     * @type {number}
     * @memberof CardOrder
     */
    'inventory'?: number;
    /**
     * The quantity of cards ordered
     * @type {number}
     * @memberof CardOrder
     */
    'quantity_ordered'?: number;
    /**
     * The unit price for the card order.
     * @type {number}
     * @memberof CardOrder
     */
    'unit_price'?: number;
    /**
     * The reason for cancellation.
     * @type {string}
     * @memberof CardOrder
     */
    'cancelled_reason'?: string;
    /**
     * A timestamp in ISO 8601 format of the date the resource was created.
     * @type {string}
     * @memberof CardOrder
     */
    'availability_date'?: string;
    /**
     * The fixed deadline for the cards to be printed.
     * @type {string}
     * @memberof CardOrder
     */
    'expected_availability_date'?: string;
    /**
     * A timestamp in ISO 8601 format of the date the resource was created.
     * @type {string}
     * @memberof CardOrder
     */
    'date_created'?: string;
    /**
     * A timestamp in ISO 8601 format of the date the resource was last modified.
     * @type {string}
     * @memberof CardOrder
     */
    'date_modified'?: string;
    /**
     * Only returned if the resource has been successfully deleted.
     * @type {boolean}
     * @memberof CardOrder
     */
    'deleted'?: boolean;
    /**
     * Value is type of resource.
     * @type {string}
     * @memberof CardOrder
     */
    'object'?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum CardOrderStatusEnum {
    Pending = 'pending',
    Printing = 'printing',
    Available = 'available',
    Cancelled = 'cancelled',
    Depleted = 'depleted'
}


