/* tslint:disable */
/* eslint-disable */
/**
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CheckBottom } from './check-bottom';
import { InlineAddressUs } from './inline-address-us';

/**
 * 
 * @export
 * @interface CheckEditablePropsAllOf
 */
export class CheckEditablePropsAllOf {
    /**
     * Must either be an address ID or an inline object with correct address parameters. Must either be an address ID or an inline object with correct address parameters. All addresses will be standardized into uppercase without being modified by verification.
     * @type {string | InlineAddressUs}
     * @memberof CheckEditablePropsAllOf
     */
    'from': string | InlineAddressUs;
    /**
     * 
     * @type {string}
     * @memberof CheckEditablePropsAllOf
     */
    'bank_account': string;
    /**
     * The payment amount to be sent in US dollars. Amounts will be rounded to two decimal places.
     * @type {number}
     * @memberof CheckEditablePropsAllOf
     */
    'amount': number;
    /**
     * Accepts a remote URL or local file upload to an image to print (in grayscale) in the upper-left corner of your check. Image requirements:    * RGB or CMYK    * square    * minimum size: 100px x 100px    * transparent backgrond    * `png` or `jpg`
     * @type {string}
     * @memberof CheckEditablePropsAllOf
     */
    'logo'?: string;
    /**
     * 
     * @type {CheckBottom}
     * @memberof CheckEditablePropsAllOf
     */
    'check_bottom'?: CheckBottom;
    /**
     * A document to include with the check.  Notes: - HTML merge variables should not include delimiting whitespace. - All pages of PDF, PNG, and JPGs must be sized at 8.5\"x11\" at 300 DPI, while supplied HTML will be rendered and trimmed to as many 8.5\"x11\" pages as necessary. - If a PDF is provided, it must be 6 pages or fewer. - The attachment will be printed double-sided in black & white and will be included in the envelope after the check page. - Please follow these [design guidelines](https://s3-us-west-2.amazonaws.com/public.lob.com/assets/templates/check_attachment_template.pdf).  See [pricing](https://lob.com/pricing/print-mail#compare) for extra costs incurred. Need more help? Consult our [HTML examples](#section/HTML-Examples).
     * @type {string}
     * @memberof CheckEditablePropsAllOf
     */
    'attachment'?: string;
    /**
     * An optional string with the billing group ID to tag your usage with. Is used for billing purposes. Requires special activation to use. See [Billing Group API](https://lob.github.io/lob-openapi/#tag/Billing-Groups) for more information.
     * @type {string}
     * @memberof CheckEditablePropsAllOf
     */
    'billing_group_id'?: string;
}


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

