/* tslint:disable */
/* eslint-disable */
/**
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)?
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as Models from "./index";

/**
 *
 * @export
 * @class CreativeWritable
 */
export class CreativeWritable {
  constructor(input?: any) {
    if (typeof input?.from !== "undefined") {
      this.from = input.from;
    }
    if (typeof input?.description !== "undefined") {
      this.description = input.description;
    }
    if (typeof input?.metadata !== "undefined") {
      this.metadata = input.metadata;
    }
    if (typeof input?.resource_type !== "undefined") {
      this.resource_type = input.resource_type;
    }
    if (typeof input?.campaign_id !== "undefined") {
      this.campaign_id = input.campaign_id;
    }
    if (typeof input?.details !== "undefined") {
      this.details = input.details;
    }
    if (typeof input?.file !== "undefined") {
      this.file = input.file;
    }
    if (typeof input?.front !== "undefined") {
      this.front = input.front;
    }
    if (typeof input?.back !== "undefined") {
      this.back = input.back;
    }
  }

  /**
   * Must either be an address ID or an inline object with correct address parameters.
   * @type {any}
   * @memberof CreativeWritable
   */

  "from": string | Models.AddressEditable;

  /**
   * An internal description that identifies this resource. Must be no longer than 255 characters.
   * @type {string}
   * @memberof CreativeWritable
   */
  "description"?: string | null;

  /**
   * Use metadata to store custom information for tagging and labeling back to your internal systems. Must be an object with up to 20 key-value pairs. Keys must be at most 40 characters and values must be at most 500 characters. Neither can contain the characters `\"` and `\\`. i.e. \'{\"customer_id\" : \"NEWYORK2015\"}\' Nested objects are not supported.  See [Metadata](#section/Metadata) for more information.
   * @type {{ [key: string]: string; }}
   * @memberof CreativeWritable
   */
  "metadata"?: { [key: string]: string };

  /**
   * Mailpiece type for the creative
   * @type {string}
   * @memberof CreativeWritable
   */
  "resource_type": CreativeWritableResourceTypeEnum;

  /**
   * Unique identifier prefixed with `cmp_`.
   * @type {string}
   * @memberof CreativeWritable
   */
  private "_campaign_id": string;
  public get campaign_id() {
    return this._campaign_id;
  }
  public set campaign_id(newValue: string) {
    if (newValue && !/^cmp_[a-zA-Z0-9]+$/.test(newValue)) {
      throw new Error("Invalid campaign_id provided");
    }
    this._campaign_id = newValue;
  }

  /**
   * Either PostcardDetailsWritable or LetterDetailsWritable
   * @type {any}
   * @memberof CreativeWritable
   */

  "details"?: Models.PostcardDetailsWritable | Models.LetterDetailsWritable;

  /**
   * PDF file containing the letter\'s formatting. Do not include for resource_type = postcard.
   * @type {string}
   * @memberof CreativeWritable
   */
  "file"?: string;

  /**
   * The artwork to use as the front of your postcard. Do not include for resource_type = letter.
   * @type {string}
   * @memberof CreativeWritable
   */
  "front"?: string;

  /**
   * The artwork to use as the back of your postcard. Do not include for resource_type = letter.
   * @type {string}
   * @memberof CreativeWritable
   */
  "back"?: string;

  public toJSON() {
    let out = {};
    for (const [key, value] of Object.entries(this)) {
      out = Object.assign({}, out, {
        [key[0] === "_" ? key.substr(1, key.length) : key]: value,
      });
    }
    return out;
  }
}

/**
 * @export
 * @enum {string}
 */
export enum CreativeWritableResourceTypeEnum {
  Letter = "letter",
  Postcard = "postcard",
}

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
