/* tslint:disable */
/* eslint-disable */
/**
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)?
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as Models from "./index";

/**
 * A nested custom envelope object containing more information about the custom envelope used or `null` if a custom envelope was not used.
 * @export
 * @class CustomEnvelopeReturned
 */
export class CustomEnvelopeReturned {
  constructor(input?: any) {
    if (typeof input?.id !== "undefined") {
      this.id = input.id;
    }
    if (typeof input?.url !== "undefined") {
      this.url = input.url;
    }
    if (typeof input?.object !== "undefined") {
      this.object = input.object;
    }
  }

  /**
   * The unique identifier of the custom envelope used.
   * @type {string}
   * @memberof CustomEnvelopeReturned
   */
  "id": string;

  /**
   * The url of the envelope asset used.
   * @type {string}
   * @memberof CustomEnvelopeReturned
   */
  "url": string;

  /**
   *
   * @type {string}
   * @memberof CustomEnvelopeReturned
   */
  "object": CustomEnvelopeReturnedObjectEnum;

  public toJSON() {
    let out = {};
    for (const [key, value] of Object.entries(this)) {
      out = Object.assign({}, out, {
        [key[0] === "_" ? key.substr(1, key.length) : key]: value,
      });
    }
    return out;
  }
}

/**
 * @export
 * @enum {string}
 */
export enum CustomEnvelopeReturnedObjectEnum {
  Envelope = "envelope",
}

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
