/* tslint:disable */
/* eslint-disable */
/**
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)?
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */

export enum DpvFootnote {
  Aa = "AA",
  A1 = "A1",
  Bb = "BB",
  Cc = "CC",
  N1 = "N1",
  F1 = "F1",
  G1 = "G1",
  U1 = "U1",
  M1 = "M1",
  M3 = "M3",
  P1 = "P1",
  P3 = "P3",
  R1 = "R1",
  R7 = "R7",
  Rr = "RR",
}

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
