/* tslint:disable */
/* eslint-disable */
/**
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as Models from './index';


/**
 * 
 * @export
 * @class EventType
 */
export class EventType {
    constructor(input?: any) {
        if (typeof input?.id !== "undefined") {
            this.id = input.id;
        }
        if (typeof input?.enabled_for_test !== "undefined") {
            this.enabled_for_test = input.enabled_for_test;
        }
        if (typeof input?.resource !== "undefined") {
            this.resource = input.resource;
        }
        if (typeof input?.object !== "undefined") {
            this.object = input.object;
        }
    }

    /**
     * 
     * @type {string}
     * @memberof EventType
     */
    'id'?: string;



    
    /**
     * Value is `true` if the event type is enabled in both the test and live environments.
     * @type {boolean}
     * @memberof EventType
     */
    'enabled_for_test'?: boolean;



    
    /**
     * 
     * @type {string}
     * @memberof EventType
     */
    'resource'?: EventTypeResourceEnum;



    
    /**
     * Value is resource type.
     * @type {string}
     * @memberof EventType
     */
    'object'?: EventTypeObjectEnum;



    
    public toJSON() {
        let out = {};
        for (const [key, value] of Object.entries(this)) {
            out = Object.assign({}, out, { [key[0] === '_' ? key.substr(1, key.length) : key]: value});
        }
        return out;
    }
}

/**
    * @export
    * @enum {string}
    */
export enum EventTypeResourceEnum {
    Postcards = 'postcards',
    SelfMailers = 'self mailers',
    Letters = 'letters',
    Checks = 'checks',
    Addresses = 'addresses',
    BankAccounts = 'bank accounts'
}
/**
    * @export
    * @enum {string}
    */
export enum EventTypeObjectEnum {
    EventType = 'event_type'
}



/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

