/* tslint:disable */
/* eslint-disable */
/**
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)?
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as Models from "./index";

/**
 *
 * @export
 * @class Export
 */
export class Export {
  constructor(input?: any) {
    if (typeof input?.id !== "undefined") {
      this.id = input.id;
    }
    if (typeof input?.dateCreated !== "undefined") {
      this.dateCreated = input.dateCreated;
    }
    if (typeof input?.dateModified !== "undefined") {
      this.dateModified = input.dateModified;
    }
    if (typeof input?.deleted !== "undefined") {
      this.deleted = input.deleted;
    }
    if (typeof input?.s3Url !== "undefined") {
      this.s3Url = input.s3Url;
    }
    if (typeof input?.state !== "undefined") {
      this.state = input.state;
    }
    if (typeof input?.type !== "undefined") {
      this.type = input.type;
    }
    if (typeof input?.uploadId !== "undefined") {
      this.uploadId = input.uploadId;
    }
  }

  /**
   * Unique identifier prefixed with `ex_`.
   * @type {string}
   * @memberof Export
   */
  private "_id": string;
  public get id() {
    return this._id;
  }
  public set id(newValue: string) {
    if (newValue && !/^ex_[a-zA-Z0-9]+$/.test(newValue)) {
      throw new Error("Invalid id provided");
    }
    this._id = newValue;
  }

  /**
   * A timestamp in ISO 8601 format of the date the export was created
   * @type {string}
   * @memberof Export
   */
  "dateCreated": string;

  /**
   * A timestamp in ISO 8601 format of the date the export was last modified
   * @type {string}
   * @memberof Export
   */
  "dateModified": string;

  /**
   * Returns as `true` if the resource has been successfully deleted.
   * @type {boolean}
   * @memberof Export
   */
  "deleted": boolean;

  /**
   * The URL for the generated export file.
   * @type {string}
   * @memberof Export
   */
  "s3Url"?: string;

  /**
   * The state of the export file, which can be `in_progress`, `failed` or `succeeded`.
   * @type {string}
   * @memberof Export
   */
  "state": ExportStateEnum;

  /**
   * The export file type, which can be `all`, `failures` or `successes`.
   * @type {string}
   * @memberof Export
   */
  "type": ExportTypeEnum;

  /**
   * Unique identifier prefixed with `upl_`.
   * @type {string}
   * @memberof Export
   */
  private "_uploadId": string;
  public get uploadId() {
    return this._uploadId;
  }
  public set uploadId(newValue: string) {
    if (newValue && !/^upl_[a-zA-Z0-9]+$/.test(newValue)) {
      throw new Error("Invalid uploadId provided");
    }
    this._uploadId = newValue;
  }

  public toJSON() {
    let out = {};
    for (const [key, value] of Object.entries(this)) {
      out = Object.assign({}, out, {
        [key[0] === "_" ? key.substr(1, key.length) : key]: value,
      });
    }
    return out;
  }
}

/**
 * @export
 * @enum {string}
 */
export enum ExportStateEnum {
  InProgress = "in_progress",
  Failed = "failed",
  Succeeded = "succeeded",
}
/**
 * @export
 * @enum {string}
 */
export enum ExportTypeEnum {
  All = "all",
  Failures = "failures",
  Successes = "successes",
}

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
