/* tslint:disable */
/* eslint-disable */
/**
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)?
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as Models from "./index";

import { GeocodeComponents } from "./geocode-components";
import { LocationAnalysis } from "./location-analysis";

/**
 *
 * @export
 * @class GeocodeAddresses
 */
export class GeocodeAddresses {
  constructor(input?: any) {
    if (typeof input?.components !== "undefined") {
      this.components = input.components;
    }
    if (typeof input?.location_analysis !== "undefined") {
      this.location_analysis = input.location_analysis;
    }
  }

  /**
   *
   * @type {GeocodeComponents}
   * @memberof GeocodeAddresses
   */
  "components"?: GeocodeComponents;

  /**
   *
   * @type {LocationAnalysis}
   * @memberof GeocodeAddresses
   */
  "location_analysis"?: LocationAnalysis;
}

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
