/* tslint:disable */
/* eslint-disable */
/**
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)?
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as Models from "./index";

/**
 *
 * @export
 * @class IdentityValidation
 */
export class IdentityValidation {
  constructor(input?: any) {
    if (typeof input?.id !== "undefined") {
      this.id = input.id;
    }
    if (typeof input?.recipient !== "undefined") {
      this.recipient = input.recipient;
    }
    if (typeof input?.primary_line !== "undefined") {
      this.primary_line = input.primary_line;
    }
    if (typeof input?.secondary_line !== "undefined") {
      this.secondary_line = input.secondary_line;
    }
    if (typeof input?.urbanization !== "undefined") {
      this.urbanization = input.urbanization;
    }
    if (typeof input?.last_line !== "undefined") {
      this.last_line = input.last_line;
    }
    if (typeof input?.score !== "undefined") {
      this.score = input.score;
    }
    if (typeof input?.confidence !== "undefined") {
      this.confidence = input.confidence;
    }
    if (typeof input?.object !== "undefined") {
      this.object = input.object;
    }
  }

  /**
   * Unique identifier prefixed with `id_validation_`.
   * @type {string}
   * @memberof IdentityValidation
   */
  private "_id"?: string;
  public get id() {
    return (this._id || undefined) as string;
  }
  public set id(newValue: string) {
    if (newValue && !/^id_validation_[a-zA-Z0-9_]+$/.test(newValue)) {
      throw new Error("Invalid id provided");
    }
    this._id = newValue;
  }

  /**
   * The intended recipient, typically a person\'s or firm\'s name.
   * @type {string}
   * @memberof IdentityValidation
   */
  "recipient"?: string | null;

  /**
   * The primary delivery line (usually the street address) of the address. Combination of the following applicable `components`: * `primary_number` * `street_predirection` * `street_name` * `street_suffix` * `street_postdirection` * `secondary_designator` * `secondary_number` * `pmb_designator` * `pmb_number`
   * @type {string}
   * @memberof IdentityValidation
   */
  "primary_line"?: string;

  /**
   * The secondary delivery line of the address. This field is typically empty but may contain information if `primary_line` is too long.
   * @type {string}
   * @memberof IdentityValidation
   */
  "secondary_line"?: string;

  /**
   * Only present for addresses in Puerto Rico. An urbanization refers to an area, sector, or development within a city. See [USPS documentation](https://pe.usps.com/text/pub28/28api_008.htm#:~:text=I51.,-4%20Urbanizations&text=In%20Puerto%20Rico%2C%20identical%20street,placed%20before%20the%20urbanization%20name.) for clarification.
   * @type {string}
   * @memberof IdentityValidation
   */
  "urbanization"?: string;

  /**
   * Combination of the following applicable `components`: * City (`city`) * State (`state`) * ZIP code (`zip_code`) * ZIP+4 (`zip_code_plus_4`)
   * @type {string}
   * @memberof IdentityValidation
   */
  "last_line"?: string;

  /**
   * A numerical score between 0 and 100 that represents the likelihood the provided name is associated with a physical address.
   * @type {number}
   * @memberof IdentityValidation
   */
  "score"?: number | null;

  /**
   * Indicates the likelihood the recipient name and address match based on our custom internal calculation. Possible values are: - `high` — Has a Lob confidence score greater than 70. - `medium` — Has a Lob confidence score between 40 and 70. - `low` — Has a Lob confidence score less than 40. - `\"\"` — No tracking data exists for this address.
   * @type {string}
   * @memberof IdentityValidation
   */
  "confidence"?: IdentityValidationConfidenceEnum;

  /**
   * Value is resource type.
   * @type {string}
   * @memberof IdentityValidation
   */
  "object"?: IdentityValidationObjectEnum;

  public toJSON() {
    let out = {};
    for (const [key, value] of Object.entries(this)) {
      out = Object.assign({}, out, {
        [key[0] === "_" ? key.substr(1, key.length) : key]: value,
      });
    }
    return out;
  }
}

/**
 * @export
 * @enum {string}
 */
export enum IdentityValidationConfidenceEnum {
  High = "high",
  Medium = "medium",
  Low = "low",
  Empty = "",
}
/**
 * @export
 * @enum {string}
 */
export enum IdentityValidationObjectEnum {
  IdValidation = "id_validation",
}

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
