/* tslint:disable */
/* eslint-disable */
/**
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IntlVerification } from './intl-verification';
import { LobError } from './lob-error';

/**
 * 
 * @export
 * @class IntlVerifications
 */
export class IntlVerifications {
    constructor(input?: any) {
        if (typeof input?.addresses !== "undefined") {
            this.addresses = input.addresses;
        }
        if (typeof input?.errors !== "undefined") {
            this.errors = input.errors;
        }
    }

    /**
     * 
     * @type {Array<IntlVerification | LobError>}
     * @memberof IntlVerifications
     */
    'addresses'?: Array<IntlVerification | LobError>;
    
    /**
     * Indicates whether any errors occurred during the verification process.
     * @type {boolean}
     * @memberof IntlVerifications
     */
    'errors'?: boolean;
    
}


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

