/* tslint:disable */
/* eslint-disable */
/**
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)?
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Lob Confidence Score is a nested object that provides a numerical value between 0-100 of the likelihood that an address is deliverable based on Lob’s mail delivery data to over half of US households.
 * @export
 * @class LobConfidenceScore
 */
export class LobConfidenceScore {
  constructor(input?: any) {
    if (typeof input?.score !== "undefined") {
      this.score = input.score;
    }
    if (typeof input?.level !== "undefined") {
      this.level = input.level;
    }
  }

  /**
   * A numerical score between 0 and 100 that represents the percentage of mailpieces Lob has sent to this addresses that have been delivered successfully over the past 2 years. Will be `null` if no tracking data exists for this address.
   * @type {number}
   * @memberof LobConfidenceScore
   */
  "score"?: number | null;

  /**
   * indicates the likelihood that the address is a valid, mail-receiving address. Possible values are:   - `high` — Over 70% of mailpieces Lob has sent to this address were delivered successfully and recent mailings were also successful.   - `medium` — Between 40% and 70% of mailpieces Lob has sent to this address were delivered successfully.   - `low` — Less than 40% of mailpieces Lob has sent to this address were delivered successfully and recent mailings weren\'t successful.   - `\"\"` — No tracking data exists for this address or lob deliverability was unable to find a corresponding level of mail success.
   * @type {string}
   * @memberof LobConfidenceScore
   */
  "level"?: LobConfidenceScoreLevelEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum LobConfidenceScoreLevelEnum {
  High = "high",
  Medium = "medium",
  Low = "low",
  Empty = "",
}

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
