/* tslint:disable */
/* eslint-disable */
/**
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Unique identifier referring to status of self mailer
 * @export
 * @enum {string}
 */

export enum SelfMailerTypes {
    Created = 'self_mailer.created',
    RenderedPdf = 'self_mailer.rendered_pdf',
    RenderedThumbnails = 'self_mailer.rendered_thumbnails',
    Deleted = 'self_mailer.deleted',
    Mailed = 'self_mailer.mailed',
    InTransit = 'self_mailer.in_transit',
    InLocalArea = 'self_mailer.in_local_area',
    ProcessedForDelivery = 'self_mailer.processed_for_delivery',
    ReRouted = 'self_mailer.re-routed',
    ReturnedToSender = 'self_mailer.returned_to_sender'
}



/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

