/* tslint:disable */
/* eslint-disable */
/**
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CountryExtended } from './country-extended';

/**
 * 
 * @export
 * @interface SingleLineAddressIntl
 */
export class SingleLineAddressIntl {
    constructor(input?: any) {
        if (typeof input?.address !== "undefined") {
            this.address = input.address;
        }
        if (typeof input?.country !== "undefined") {
            this.country = input.country;
        }
    }

    /**
     * The entire address in one string (e.g., \"370 Water St C1N 1C4\"). 
     * @type {string}
     * @memberof SingleLineAddressIntl
     */
    'address'?: string;
    
    /**
     * 
     * @type {CountryExtended}
     * @memberof SingleLineAddressIntl
     */
    'country'?: CountryExtended;
    
}


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

