/* tslint:disable */
/* eslint-disable */
/**
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SortBy
 */
export class SortBy {
    constructor(input?: any) {
        if (input) {
            if (typeof input.date_created !== "undefined") {
                this.date_created = input.date_created;
            }
            if (typeof input.send_date !== "undefined") {
                this.send_date = input.send_date;
            }
        }
    }

    /**
     * 
     * @type {string}
     * @memberof SortBy
     */
    'date_created'?: SortByDateCreatedEnum;
    
    /**
     * 
     * @type {string}
     * @memberof SortBy
     */
    'send_date'?: SortBySendDateEnum;
    
}

/**
    * @export
    * @enum {string}
    */
export enum SortByDateCreatedEnum {
    Asc = 'asc',
    Desc = 'desc'
}
/**
    * @export
    * @enum {string}
    */
export enum SortBySendDateEnum {
    Asc = 'asc',
    Desc = 'desc'
}



/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

