/* tslint:disable */
/* eslint-disable */
/**
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)?
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as Models from "./index";

/**
 *
 * @export
 * @class UsCsvVerificationsResponse
 */
export class UsCsvVerificationsResponse {
  constructor(input?: any) {
    if (typeof input?.csv_id !== "undefined") {
      this.csv_id = input.csv_id;
    }
    if (typeof input?.status !== "undefined") {
      this.status = input.status;
    }
  }

  /**
   * Unique identifier prefixed with csv_ver.
   * @type {string}
   * @memberof UsCsvVerificationsResponse
   */
  "csv_id"?: string;

  /**
   * Current status of your CSV verification. One of: * Received * Preprocessing * Verification * Emailing
   * @type {string}
   * @memberof UsCsvVerificationsResponse
   */
  "status"?: string;

  public toJSON() {
    let out = {};
    for (const [key, value] of Object.entries(this)) {
      out = Object.assign({}, out, {
        [key[0] === "_" ? key.substr(1, key.length) : key]: value,
      });
    }
    return out;
  }
}

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
