/* tslint:disable */
/* eslint-disable */
/**
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ZipCodeType } from './zip-code-type';
import { ZipLookupCity } from './zip-lookup-city';

/**
 * 
 * @export
 * @interface ZipAllOf
 */
export class ZipAllOf {
    /**
     * Unique identifier prefixed with `us_zip_`.
     * @type {string}
     * @memberof ZipAllOf
     */
    private '_id': string;
    public get id() { return (this._id); }
    public set id(newValue: string) {
        if(newValue && !/^us_zip_[a-zA-Z0-9]+$/.test(newValue)) {
            throw new Error("Invalid id provided");
        }
        this._id = newValue;
    }
    /**
     * An array of city objects containing valid cities for the `zip_code`. Multiple cities will be returned if more than one city is associated with the input ZIP code. 
     * @type {Array<ZipLookupCity>}
     * @memberof ZipAllOf
     */
    'cities': Array<ZipLookupCity>;
    /**
     * 
     * @type {ZipCodeType}
     * @memberof ZipAllOf
     */
    'zip_code_type': ZipCodeType;
    /**
     * 
     * @type {string}
     * @memberof ZipAllOf
     */
    'object': string;
}


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

