/* tslint:disable */
/* eslint-disable */
/**
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)?
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as Models from "./index";

import { ZipCodeType } from "./zip-code-type";
import { ZipLookupCity } from "./zip-lookup-city";

/**
 *
 * @export
 * @class Zip
 */
export class Zip {
  constructor(input?: any) {
    if (typeof input?.zip_code !== "undefined") {
      this.zip_code = input.zip_code;
    }
    if (typeof input?.id !== "undefined") {
      this.id = input.id;
    }
    if (typeof input?.cities !== "undefined") {
      this.cities = input.cities;
    }
    if (typeof input?.zip_code_type !== "undefined") {
      this.zip_code_type = input.zip_code_type;
    }
    if (typeof input?.object !== "undefined") {
      this.object = input.object;
    }
  }

  /**
   * A 5-digit ZIP code.
   * @type {string}
   * @memberof Zip
   */
  private "_zip_code"?: string;
  public get zip_code() {
    return (this._zip_code || undefined) as string;
  }
  public set zip_code(newValue: string) {
    if (newValue && !/^\d{5}$/.test(newValue)) {
      throw new Error("Invalid zip_code provided");
    }
    this._zip_code = newValue;
  }

  /**
   * Unique identifier prefixed with `us_zip_`.
   * @type {string}
   * @memberof Zip
   */
  private "_id"?: string;
  public get id() {
    return (this._id || undefined) as string;
  }
  public set id(newValue: string) {
    if (newValue && !/^us_zip_[a-zA-Z0-9]+$/.test(newValue)) {
      throw new Error("Invalid id provided");
    }
    this._id = newValue;
  }

  /**
   * An array of city objects containing valid cities for the `zip_code`. Multiple cities will be returned if more than one city is associated with the input ZIP code.
   * @type {Array<ZipLookupCity>}
   * @memberof Zip
   */
  "cities"?: Array<ZipLookupCity>;

  /**
   *
   * @type {ZipCodeType}
   * @memberof Zip
   */
  "zip_code_type"?: ZipCodeType;

  /**
   *
   * @type {string}
   * @memberof Zip
   */
  "object"?: ZipObjectEnum;

  public toJSON() {
    let out = {};
    for (const [key, value] of Object.entries(this)) {
      out = Object.assign({}, out, {
        [key[0] === "_" ? key.substr(1, key.length) : key]: value,
      });
    }
    return out;
  }
}

/**
 * @export
 * @enum {string}
 */
export enum ZipObjectEnum {
  UsZipLookup = "us_zip_lookup",
}

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
